export const boardHtml = `<!doctype html>
<html lang="zh-Hans"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Leo Dev 看板</title><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/board.css"></head>
<body><header><strong>Leo Dev</strong><span id="identity">Loading observation…</span><button id="refresh" type="button">刷新</button></header><main><p id="notice" role="status" aria-live="polite"></p><section id="columns" aria-label="Task board"></section><aside id="detail" aria-live="polite"><h2>Task detail</h2><p>Select a task to inspect its recorded evidence.</p></aside><section id="team" aria-label="Recorded team"></section></main><script src="/assets/board.js" defer></script></body></html>`;

export const boardCss = `:root{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#111;background:#FFF6E8}*{box-sizing:border-box}body{margin:0;overflow-wrap:anywhere}header{display:flex;align-items:center;gap:16px;padding:14px 20px;background:#E23C2F;color:#fff}header strong{color:#fff}header span{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.85rem;flex:1;min-width:0;overflow-wrap:anywhere}button{font:inherit;border:2px solid #111;border-radius:8px;background:#fff;color:#111;padding:7px 10px;cursor:pointer}button:focus-visible{outline:3px solid #111;outline-offset:2px}main{padding:18px;min-width:0}#notice{min-height:1.4em;color:#627084;overflow-wrap:anywhere}#notice[data-state="stale"],.blocked{color:#996316}#columns{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.column{min-width:0;background:#fff;border:3px solid #111;border-radius:16px;min-height:180px;padding:10px}.column h2{font-size:.9rem;margin:0 0 9px;color:#111}.card{display:block;width:100%;min-width:0;margin:8px 0;text-align:left;overflow-wrap:anywhere;border:3px solid #111;border-radius:16px;background:#fff}.card small{display:block;color:#627084;margin-top:4px}.badge{display:inline-block;margin-top:6px;padding:2px 8px;border:2px solid #111;border-radius:999px;font-size:12px}.badge-reviewing{background:#FFE066}.badge-rejected{background:#FF8A80}.evidence{min-width:0;overflow-wrap:anywhere;word-break:break-word;border-top:1px solid #e5eaf1;margin-top:6px;padding-top:5px;font:12px ui-monospace,SFMono-Regular,Menlo,monospace}aside,#team{min-width:0;overflow-wrap:anywhere;margin-top:16px;background:#fff;border:3px solid #111;border-radius:16px;padding:12px}aside h2,#team h2{margin-top:0}@media(max-width:760px){#columns{grid-template-columns:1fr}header{align-items:flex-start;padding:12px;gap:10px}main{padding:12px}}@media(prefers-reduced-motion:no-preference){.card{transition:box-shadow .12s}.card:hover{box-shadow:0 2px 8px #111}}`;

export const boardJs = `(() => {
  const columns = document.getElementById('columns'); const notice = document.getElementById('notice'); const identity = document.getElementById('identity'); const detail = document.getElementById('detail'); const team = document.getElementById('team');
  const names = {todo:'待办',doing:'进行中',done:'完成'};
  let latest = null; let selectedTaskId = null;
  function text(node, value){node.textContent = value == null ? 'unknown' : String(value);}
  function evidence(parent, label, value, compact=false){const line=document.createElement('div');line.className='evidence';const fields=value?(compact?[value.status,'candidate '+value.currentCandidate]:[value.status,'candidate '+value.currentCandidate,value.runId&&'run '+value.runId,value.candidateTreeHash&&'tree '+value.candidateTreeHash,value.evidenceRef&&'evidence '+value.evidenceRef]).filter(Boolean):['unknown'];text(line,label+': '+fields.join(' · '));parent.append(line);}
  function select(task){selectedTaskId=task.id;detail.replaceChildren();const h=document.createElement('h2');text(h,task.id);detail.append(h);const state=document.createElement('p');text(state,'Recorded state: '+task.state+' · revision '+task.revision+' · run '+(task.runId||'unknown')+' · assignment '+(task.assignmentSession||'unknown')+' · run state '+(task.runState||'unknown')+' · lease active '+(task.leaseActive==null?'unknown':task.leaseActive)+' · last activity '+(task.lastActivity||'unknown'));detail.append(state);const req=document.createElement('ul');for(const item of task.requirements||[]){const li=document.createElement('li');text(li,item);req.append(li)}detail.append(req);for(const blocker of task.blockers||[]){const line=document.createElement('p');text(line,'Recorded blocker '+blocker.blockerId+': '+(blocker.reason||'unknown')+' · '+blocker.recordedAt);detail.append(line)}evidence(detail,'Gate',task.gate);evidence(detail,'Review',task.review);}
  function resetDetail(){selectedTaskId=null;detail.replaceChildren();const h=document.createElement('h2');text(h,'Task detail');detail.append(h);const p=document.createElement('p');text(p,'Select a task to inspect its recorded evidence.');detail.append(p)}
  function renderTeam(value){team.replaceChildren();const h=document.createElement('h2');text(h,'Recorded team · host liveness unknown');team.append(h);if(!value){const p=document.createElement('p');text(p,'No recorded team.');team.append(p);return}const p=document.createElement('p');text(p,value.teamId+' · revision '+value.revision);team.append(p);const list=document.createElement('ul');for(const member of value.members){const li=document.createElement('li');text(li,member.memberId+' · '+member.role+' · generation '+member.generation+' · '+(member.threadId||'unbound')+' · last activity '+(member.lastRecordedActivity||'unknown'));list.append(li)}team.append(list);for(const message of value.messages||[]){const line=document.createElement('p');text(line,message.kind+' '+message.messageId+' · '+message.fromMemberId+' → '+message.toMemberId+' · '+message.status+' · '+(message.recordedAt||'unknown'));team.append(line)}}
  function renderColumns(tasks){columns.replaceChildren();for(const key of Object.keys(names)){const column=document.createElement('section');column.className='column';const heading=document.createElement('h2');text(heading,names[key]);column.append(heading);const grouped=tasks.filter((candidate)=>candidate.column===key);if(!grouped.length){const empty=document.createElement('small');text(empty,'No recorded tasks.');column.append(empty)}for(const task of grouped){const card=document.createElement('button');card.type='button';card.className='card'+(task.blocked?' blocked':'');card.addEventListener('click',()=>select(task));text(card,task.title);const meta=document.createElement('small');text(meta,task.state+' · r'+task.revision);card.append(meta);if(task.reviewBadge&&task.reviewBadge!=='none'){const badge=document.createElement('span');badge.className='badge badge-'+task.reviewBadge;text(badge,task.reviewBadge==='reviewing'?'审查中':'审查未过');card.append(badge)}evidence(card,'Gate',task.gate,true);evidence(card,'Review',task.review,true);column.append(card)}columns.append(column)}}
  function render(value){text(identity,value.changeId+' · '+value.repositoryRoot);if(value.availability!=='available'){notice.dataset.state='stale';text(notice,'Observation unavailable; last successful observation may be stale: '+(value.blocker&&value.blocker.message||'unknown'));if(!latest){renderColumns([]);renderTeam(null);resetDetail()}return;}latest=value;notice.dataset.state='';const blockers=value.change&&value.change.blockers||[];text(notice,'Recorded '+value.observedAt+' · revision '+(value.change&&value.change.revision)+' · host live status: unknown'+(blockers.length?' · recorded blockers: '+blockers.map((item)=>item.blockerId+': '+(item.reason||'unknown')).join(', '):''));renderColumns(value.tasks||[]);renderTeam(value.recordedTeam);const selected=(value.tasks||[]).find((task)=>task.id===selectedTaskId);if(selected)select(selected);else resetDetail()}
  async function refresh(){try{const response=await fetch('/api/observation',{headers:{Accept:'application/json'}});if(!response.ok)throw new Error('HTTP '+response.status);render(await response.json())}catch(error){notice.dataset.state='stale';text(notice,'Refresh failed; last observation may be stale: '+error.message)}}
  document.getElementById('refresh').addEventListener('click',refresh);refresh();
})();`;

export const boardFavicon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><rect width="16" height="16" rx="4" fill="#FFF6E8"/><circle cx="8" cy="8.5" r="5.2" fill="#F5C9A8" stroke="#111" stroke-width="1.2"/><rect x="3.9" y="5.9" width="3.4" height="1.4" rx=".2" fill="#111"/><rect x="8.7" y="5.9" width="3.4" height="1.4" rx=".2" fill="#111"/><circle cx="6.1" cy="9" r=".55" fill="#111"/><circle cx="9.9" cy="9" r=".55" fill="#111"/><path d="M6.1 11.1c.7.7 3.1.7 3.8 0" fill="none" stroke="#E23C2F" stroke-width="1.1" stroke-linecap="round"/></svg>`;
